In [4]:
import numpy as np

data=np.load('data-mobile-net-more.npy')
target=np.load('target-mobile-net-more.npy')
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model

def load_cnn():

        baseModel= MobileNetV2(weights='imagenet',include_top=False,input_tensor=Input(shape=(224,224,3)))

        headModel= baseModel.output
        headModel= AveragePooling2D(pool_size=(4,4),padding='same')(headModel)
        headModel= Flatten(name="flatten")(headModel)
        headModel= Dense(128,activation='relu')(headModel)
        headModel= Dropout(0.5)(headModel)
        headModel= Dense(2,activation="softmax")(headModel)

        model= Model(inputs=baseModel.input,outputs=headModel)

        for layer in baseModel.layers:
                 
                layer.trainable = False
    
        model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=["accuracy"])
        model=load_model('AdultKid-mobile-net98.h5')

        return model

In [2]:
import cv2,os
from tensorflow.keras.models import Model
test_path='test1'
img_names=os.listdir(test_path)
model=load_cnn()
category={0:'Adult',1:'Kid'}
for img_name in img_names:
    img_path=os.path.join(test_path,img_name)
    img=cv2.imread(img_path)
    #gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    resized=cv2.resize(img,(224,224))
    normalized=resized/255.0
    reshaped=np.reshape(normalized,(1,224,224,3))
    
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    
    img[:10,:]=[0,255,0]
    cv2.putText(img,str(category[label]),(100,100),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
    #cv2.putText(img,str(prob),(100,10),cv2.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv2.imshow('LIVE',img)
    cv2.waitKey(2000)
    print(result)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


C:\Users\Ayodhya\anaconda3\lib\site-packages\keras_applications\mobilenet_v2.py:294: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[[9.997472e-01 2.527683e-04]]
[[1.8634282e-04 9.9981374e-01]]
[[1.489326e-04 9.998510e-01]]
[[0.46731207 0.5326879 ]]
[[0.91346496 0.08653506]]
[[0.38580373 0.6141963 ]]
[[0.0973352 0.9026648]]
[[9.9965584e-01 3.4413001e-04]]
[[0.99804425 0.00195574]]
[[0.9580747 0.0419253]]
[[0.01545634 0.9845436 ]]
[[9.9996185e-01 3.8176142e-05]]
[[0.20043486 0.79956514]]
[[0.09284917 0.90715086]]
[[0.00310855 0.99689144]]


In [3]:
import cv2,os
from tensorflow.keras.models import Model

model=load_cnn()
category={0:'Adult',1:'Kid'}
video=cv2.VideoCapture(r'test1.mp4')

while(True):
    ret,img=video.read()
    
    resized=cv2.resize(img,(224,224))
    normalized=resized/255.0
    reshaped=np.reshape(normalized,(1,224,224,3))
    
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
    
    img[:10,:]=[0,255,0]
    cv2.putText(img,str(category[label]),(100,100),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
    #cv2.putText(img,str(prob),(100,10),cv2.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv2.imshow('LIVE',img)
    #cv2.waitKey(2000)
    print(result)
    k=cv2.waitKey(1)
    if(k==27):
        break
cv2.destroyAllWindows()

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


C:\Users\Ayodhya\anaconda3\lib\site-packages\keras_applications\mobilenet_v2.py:294: UserWarning: `input_shape` is undefined or non-square, or `rows` is not in [96, 128, 160, 192, 224]. Weights for input shape (224, 224) will be loaded as the default.
  warnings.warn('`input_shape` is undefined or non-square, '


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]
[[9.510960e-05 9.999049e-01]]


KeyboardInterrupt: 